//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soubory {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Soubory.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Popis:
        ///------
        ///1) Všechny rozpustné soli prudce jedovaté
        ///2) Měkký, lehký, reaktivní kov
        ///3) Dobrý vodič elektrického proudu a tepla
        ///4) Vysoce reaktivní
        ///
        ///Využití (příklady):
        ///-------------------
        ///1) Výroba pyrotechniky (barví plamen světle zeleně)
        ///2) Peroxid barnatý používán k bělení hedvábí.
        /// </summary>
        public static string Baryum {
            get {
                return ResourceManager.GetString("Baryum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Popis:
        ///------
        ///1) Tvrdý, křehký kov
        ///2) Těžce tavitelný
        ///3) Špatný vodič elektrického proudu a tepla
        ///4) V prášku vyvolává ekzémy a poškozuje dýchací cesty
        ///
        ///Využití (příklady):
        ///-------------------
        ///1) Ve šperkařství jako drahokamy a polodrahokamy
        ///2) Konstrukce vysokotónových reprodukturů
        ///3) Výroba nejiskřivého ručního nářadí.
        /// </summary>
        public static string Beryllium {
            get {
                return ResourceManager.GetString("Beryllium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Popis:
        ///------
        ///
        ///
        ///Využití (příklady):
        ///-------------------
        ///.
        /// </summary>
        public static string Bohrium {
            get {
                return ResourceManager.GetString("Bohrium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Popis:
        ///------
        ///1) Měkký, lehký kov, který lze krájet nožem
        ///2) Stříbrozlatý
        ///3) Dobrý vodič elektrického proudu a tepla
        ///4) Nejměkčí prvek periodické soustavy
        ///5) Druhý nejnižší bod varu a tání (ze všech kovů)
        ///
        ///Využití (příklady):
        ///-------------------
        ///1) Přístroje pro noční vidění
        ///2) Příprava velmi hustých výplachů pro hlubinné vrtání.
        /// </summary>
        public static string Cesium {
            get {
                return ResourceManager.GetString("Cesium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Popis:
        ///------
        ///1) Lesklý, světle šedý kov
        ///2) Velmi tvrdý a křehký
        ///
        ///Využití (příklady):
        ///-------------------
        ///1) Metalurgie (výroba legovaných ocelí)
        ///2) Povrchová úprava kovů
        ///.
        /// </summary>
        public static string Chrom {
            get {
                return ResourceManager.GetString("Chrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Popis:
        ///------
        ///1) Měkký, lehký kov, který lze krájet nožem
        ///2) Stříbrolesklý
        ///3) Dobrý vodič elektrického proudu a tepla
        ///
        ///Využití (příklady):
        ///-------------------
        ///1) Výroba fotoelktrických článků
        ///2) Redukční reakce v organické syntéze.
        /// </summary>
        public static string Draslík {
            get {
                return ResourceManager.GetString("Draslík", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Popis:
        ///------
        ///1) Silně radioaktivní prvek
        ///2) Příprava v jaderném reaktoru nebo urychlovači částic
        ///3) Prvek nebyl dostatečně izolován, proto nebylo možné zjistit všechny jeho fyzikální vlastnosti
        ///4) Mělo by připomínat tantal (díky své poloze v periodické tabulce)
        ///5) Pojmenováno podle města Dubna, kde bylo poprvé připraveno
        ///.
        /// </summary>
        public static string Dubnium {
            get {
                return ResourceManager.GetString("Dubnium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Popis:
        ///------
        ///1) Nestabilní, velmi silně radioaktivní prvek
        ///2) Nejtěžší z alkalických kovů
        ///.
        /// </summary>
        public static string Francium {
            get {
                return ResourceManager.GetString("Francium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Popis:
        ///------
        ///1) Šedý až stříbřitě bílý kov
        ///2) Chemicky velice podobný Zirkoniu
        ///3) Středně těžký a tvrdý
        ///4) Řídký výskyt
        ///
        ///Využití (příklady):
        ///-------------------
        ///1) Řídící tyče jaderných ponorek
        ///2) Elektrody pro plazmové řezání kovů a sváření
        ///3) Výroba klasických žárovkových vláken
        ///.
        /// </summary>
        public static string Hafnium {
            get {
                return ResourceManager.GetString("Hafnium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Popis:
        ///------
        ///
        ///
        ///Využití (příklady):
        ///-------------------
        ///.
        /// </summary>
        public static string Hassium {
            get {
                return ResourceManager.GetString("Hassium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Popis:
        ///------
        ///1) Středně tvrdý, lehký, tažný kov
        ///2) Vyšší hustota než voda
        ///3) Hůře vede elektrický proud a teplo
        ///
        ///Využití (příklady):
        ///-------------------
        ///1) Slitiny s hliníkem, mědí a manganem - dural se používají např. v leteckém a automobilovém průmyslu
        ///2) Redukce v organické syntéze a redukční výroba jiných kovů (např. uranu).
        /// </summary>
        public static string Hořčík {
            get {
                return ResourceManager.GetString("Hořčík", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Aplikace Chemie.
        ///--------------------
        ///
        ///Zdroje:
        ///--------
        ///Informace o prvcích pocházejí z webu Wikipedia.
        ///GHS icons are downloaded from: https://unece.org/transport/dangerous-goods/ghs-pictograms
        ///Popisky k GHS ikonám jsou odsud: https://echa.europa.eu/cs/regulations/clp/clp-pictograms
        ///
        ///Novinky ()
        ///--------------------
        ///1) Implementace S a R vět
        ///2) Začátek práce na sekci &quot;teorie&quot;
        ///3) Začátek práce na sekci &quot;převody&quot;
        ///4) Menší designové úpravy
        ///5) Dokončeny stránky popisující piktogramy nebezpečí
        ///6)  [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Popis:
        ///------
        ///1) Velmi lehký, měkký kov
        ///2) Lze krájet nožem
        ///3) Dobrý vodič elektrického proudu a tepla
        ///4) Nejmenší hustota ze všech pevných prvků
        ///5) Lehčí než voda
        ///6) Reaguje s vodou
        ///
        ///Využití (příklady):
        ///-------------------
        ///1) Jaderná energetika (v některých reaktorech slouží k odvodu tepla)
        ///2) Lithiové baterie
        ///3) Organické soli jako součást při výrobě léčiv
        ///.
        /// </summary>
        public static string Lithium {
            get {
                return ResourceManager.GetString("Lithium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Popis:
        ///------
        ///
        ///
        ///Využití (příklady):
        ///-------------------
        ///.
        /// </summary>
        public static string Mangan {
            get {
                return ResourceManager.GetString("Mangan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Popis:
        ///------
        ///1) Stříbřitý až šedobílý
        ///2) Tvrdý a křehký kov
        ///3) Vysoký bod tání
        ///4) Při teplotách pod 0,915 K je supravodič
        ///
        ///Využití (příklady):
        ///-------------------
        ///1) Metalurgie (výroba speciálních ocelí)
        ///2) Některé jeho sloučeniny se využívají jako umělá hnojiva
        ///3) Výroba petrochemických katalyzátorů (slouží k odstranění sirných sloučenin z ropy).
        /// </summary>
        public static string Molybden {
            get {
                return ResourceManager.GetString("Molybden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Popis:
        ///------
        ///1) Kujný kov
        ///2) Šedá barva
        ///3) Při dlouhodobém působení vzduchu modrá
        ///
        ///Využití (příklady):
        ///-------------------
        ///1) Svařování obloukem
        ///2) Díky namodralé barvě ve slitinách piercingu
        ///3) Klenotnictví
        ///4) Medicína
        ///.
        /// </summary>
        public static string Niob {
            get {
                return ResourceManager.GetString("Niob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Popis:
        ///------
        ///
        ///
        ///Využití (příklady):
        ///-------------------
        ///.
        /// </summary>
        public static string Osmium {
            get {
                return ResourceManager.GetString("Osmium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný &lt;infooprvku&gt;
        ///	&lt;!--Vodík--&gt;
        ///	&lt;Vodík Sekce=&quot;Název&quot; Info=&quot;Vodík&quot; /&gt;
        ///	&lt;Vodík Sekce=&quot;Chemická značka&quot; Info=&quot;H&quot; /&gt;
        ///	&lt;Vodík Sekce=&quot;Protonové číslo&quot; Info=&quot;1&quot; /&gt;
        ///	&lt;Vodík Sekce=&quot;Latinsky&quot; Info=&quot;Hydrogenium&quot; /&gt;
        ///	&lt;Vodík Sekce=&quot;Skupina&quot; Info=&quot;1. skupina&quot; /&gt;
        ///	&lt;Vodík Sekce=&quot;Perioda&quot; Info=&quot;1. perioda&quot; /&gt;
        ///	&lt;Vodík Sekce=&quot;Vlastnosti&quot; Info=&quot;Bezbarvý plyn&quot; /&gt;
        ///	&lt;Vodík Sekce=&quot;Relativní atomová hmotnost&quot; Info=&quot;1,007 94&quot; /&gt;
        ///
        ///	&lt;!--Lithium--&gt;
        ///	&lt;Lithium Sekce=&quot;Název&quot; Info=&quot;Lithium&quot; /&gt;
        ///	&lt;Lithium Sekce=&quot;Chemická značka&quot; Inf [zbytek řetězce byl zkrácen];.
        /// </summary>
        public static string prvky {
            get {
                return ResourceManager.GetString("prvky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Popis:
        ///------
        ///1) Mimořádně silný radioaktivní zářič
        ///2) Bílý, těžký, velmi reaktivní kov
        ///
        ///Využití (příklady):
        ///-------------------
        ///1) Dříve při léčbě rakovinných nádorů.
        /// </summary>
        public static string Radium {
            get {
                return ResourceManager.GetString("Radium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Popis:
        ///------
        ///
        ///
        ///Využití (příklady):
        ///-------------------
        ///.
        /// </summary>
        public static string Rhenium {
            get {
                return ResourceManager.GetString("Rhenium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Popis:
        ///------
        ///1) Měkký, lehký kov, který lze krájet nožem
        ///2) Stříbrolesklý
        ///3) Dobrý vodič elektrického proudu a tepla
        ///
        ///Využití (příklady):
        ///-------------------
        ///1) Zábavní pyrotechnika - barví efekty do fialova
        ///2) Fotočlánky sloužící k přímé přeměně světelné energie v elektrickou.
        /// </summary>
        public static string Rubidium {
            get {
                return ResourceManager.GetString("Rubidium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Popis:
        ///------
        ///
        ///
        ///Využití (příklady):
        ///-------------------
        ///.
        /// </summary>
        public static string Ruthenium {
            get {
                return ResourceManager.GetString("Ruthenium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Popis:
        ///------
        ///1) Silně radioaktivní kovový prvek
        ///2) Připravovaný uměle
        ///3) Prvek nebyl dostatečně izolován, proto nebylo možné zjistit všechny jeho fyzikální vlastnosti
        ///4) Pojmenován na základě jaderného fyzika Ernesta Rutherforda
        ///.
        /// </summary>
        public static string Rutherfordium {
            get {
                return ResourceManager.GetString("Rutherfordium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Popis:
        ///------
        ///1) Silně radioaktivní prvek
        ///2) Příprava v cyklotronu nebo urychlovači částic
        ///3) Prvek nebyl dostatečně izolován, proto nebylo možné zjistit všechny jeho fyzikální vlastnosti
        ///4) Mělo by připomínat wolfram (díky své poloze v periodické tabulce)
        ///5) Pojmenováno na počest amerického jaderného fyzika Glena T. Seaborga 
        ///.
        /// </summary>
        public static string Seaborgium {
            get {
                return ResourceManager.GetString("Seaborgium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Popis:
        ///------
        ///1) Měkký kov
        ///2) Stříbřitě bílý
        ///3) Lehký
        ///
        ///Využití (příklady):
        ///-------------------
        ///1) Výroba vysoce intenzivních zdrojů světla
        ///2) Konstrukční kov v kosmonautice.
        /// </summary>
        public static string Skandium {
            get {
                return ResourceManager.GetString("Skandium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Popis:
        ///------
        ///1) Měkký, lehký kov, který lze krájet nožem
        ///2) Stříbrolesklý
        ///3) Dobrý vodič elektrického proudu a tepla
        ///
        ///Využití (příklady):
        ///-------------------
        ///1) Jaderná energetika a letecké motory - odvod tepla
        ///2) Redukční činidlo - používán v organických syntetických reakcích
        ///3) Přídavek do neonových lamp.
        /// </summary>
        public static string Sodík {
            get {
                return ResourceManager.GetString("Sodík", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Popis:
        ///------
        ///1) Měkký, lehký, reaktivní kov
        ///2) Stříbrolesklý bílý kov
        ///3) Dobrý vodič elektrického proudu a tepla
        ///
        ///Využití (příklady):
        ///-------------------
        ///1) Výroba pyrotechniky (výrazná barevná reakce)
        ///2) Uhličitan strotnatý (SrCO3) se používá při výrobě barevných televizních obrazovek.
        /// </summary>
        public static string Stroncium {
            get {
                return ResourceManager.GetString("Stroncium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Popis:
        ///------
        ///1) Vzácný kov
        ///2) Tvrdý
        ///3) Modro-šedý
        ///4) Korozivzdorný
        ///
        ///Využití (příklady):
        ///-------------------
        ///1) Elektronické součástky (kondenzátory)
        ///2) Výroba chirurgických nástrojů a implantátů.
        /// </summary>
        public static string Tantal {
            get {
                return ResourceManager.GetString("Tantal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Popis:
        ///------
        ///
        ///
        ///Využití (příklady):
        ///-------------------
        ///.
        /// </summary>
        public static string Technecium {
            get {
                return ResourceManager.GetString("Technecium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Popis:
        ///------
        ///1) Lehký kov
        ///2) Šedý až stříbřitě bílý
        ///3) Hojně zastoupený v zemské kůře
        ///4) V přírodě se vyskytuje pouze jako oxid
        ///
        ///
        ///Využití (příklady):
        ///-------------------
        ///1) Kosmonautika
        ///2) Letecký průmysl
        ///3) Piercingové ozdoby.
        /// </summary>
        public static string Titan {
            get {
                return ResourceManager.GetString("Titan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Popis:
        ///------
        ///1) Tvrdý, kujný kov
        ///2) Šedo-bílý
        ///3) Pod 5,38 K supravodivý
        ///4) Vysoké teploty tání a varu
        ///
        ///Využití (příklady):
        ///-------------------
        ///1) Výroba elektrických článků
        ///2) Výroba leteckých motorů a speciálních součástek pro konstrukci letadel a kosmických družic
        ///3) Přidává se do vysoce kvalitních ocelí
        ///.
        /// </summary>
        public static string Vanad {
            get {
                return ResourceManager.GetString("Vanad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Popis:
        ///------
        ///1) Měkký, lehký, reaktivní kov
        ///2) Dobrý vodič elektrického proudu a tepla
        ///3) Stříbrolesklý
        ///
        ///Využití (příklady):
        ///-------------------
        ///1) Díky velké reaktivitě používán v metalurgii k odstraňování síry a kyslíku a při výrobě oceli
        ///2) Redukce v organické syntéze.
        /// </summary>
        public static string Vápník {
            get {
                return ResourceManager.GetString("Vápník", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Popis:
        ///------
        ///1) Plyn bez chuti, barvy a zápachu
        ///2) Nejlehčí a nejjednodušší plynný prvek
        ///3) Převážná část hmoty ve vesmíru
        ///4) Hoří namodralým plamenem
        ///
        ///Využití (příklady):
        ///-------------------
        ///1) Raketové palivo
        ///2) Zdroj energie
        ///3) Do 30. let 20. století byl používán do vzducholodí 
        ///4) Chladivo alternátorů v elektrárnách
        ///5) Výroba Amoniaku.
        /// </summary>
        public static string Vodík {
            get {
                return ResourceManager.GetString("Vodík", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Popis:
        ///------
        ///1) Šedý až stříbřitě bílý kov
        ///2) Velmi těžký
        ///3) Obtížně tavitelný 
        ///
        ///Využití (příklady):
        ///-------------------
        ///1) Žárovková vlákna
        ///2) Wolframové elektrody při svařování (metoda TIG)
        ///.
        /// </summary>
        public static string Wolfram {
            get {
                return ResourceManager.GetString("Wolfram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Popis:
        ///------
        ///1) Stříbřitě bílý
        ///2) Středně tvrdý kov
        ///3) Poměrně vzácný
        ///
        ///Využití (příklady):
        ///-------------------
        ///1) Výroba vakuových obrazovek televizorů
        ///2) Výroba šperků (levná náhrada diamantu)
        ///.
        /// </summary>
        public static string Yttrium {
            get {
                return ResourceManager.GetString("Yttrium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Popis:
        ///------
        ///
        ///
        ///Využití (příklady):
        ///-------------------
        ///.
        /// </summary>
        public static string Železo {
            get {
                return ResourceManager.GetString("Železo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Popis:
        ///------
        ///1) Šedý až stříbřitě bílý kov
        ///2) Velice odolný proti korozi
        ///3) Tvrdý a lehký kov
        ///
        ///
        ///Využití (příklady):
        ///-------------------
        ///1) Povrchová ochrana kovů
        ///2) Při výrobě elektřiny v jaderných elektrárnách
        ///3) Výroba zápalných bomb pro vojenské účely
        ///.
        /// </summary>
        public static string Zirkonium {
            get {
                return ResourceManager.GetString("Zirkonium", resourceCulture);
            }
        }
    }
}
