//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Soubory {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Soubory.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekt aplikace Chemie.
        ///Informace o prvcích pocházejí z webu Wikipedia.
        ///
        ///Změny:
        ///------
        ///1) Vylepšený design aplikace
        ///2) Nové okno &quot;O aplikaci&quot;
        ///3) Možnost zavírat okna &quot;O aplikaci&quot; a &quot;Info o prvku&quot; pomocí klávesy ESC.
        ///4) Možnost přesouvání hlavního okna aplikace po obrazovce
        ///5) Lepší vykreslování
        ///.
        /// </summary>
        public static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;infooprvku&gt;
        ///	&lt;!--Vodík--&gt;
        ///	&lt;Vodík Sekce=&quot;Název&quot; Info=&quot;Vodík&quot; /&gt;
        ///	&lt;Vodík Sekce=&quot;Chemická značka&quot; Info=&quot;H&quot; /&gt;
        ///	&lt;Vodík Sekce=&quot;Protonové číslo&quot; Info=&quot;1&quot; /&gt;
        ///	&lt;Vodík Sekce=&quot;Latinsky&quot; Info=&quot;Hydrogenium&quot; /&gt;
        ///	&lt;Vodík Sekce=&quot;Skupina&quot; Info=&quot;1. skupina&quot; /&gt;
        ///	&lt;Vodík Sekce=&quot;Perioda&quot; Info=&quot;1. perioda&quot; /&gt;
        ///	&lt;Vodík Sekce=&quot;Vlastnosti&quot; Info=&quot;Bezbarvý plyn&quot; /&gt;
        ///	&lt;Vodík Sekce=&quot;Relativní atomová hmotnost&quot; Info=&quot;1,007 94&quot; /&gt;
        ///	&lt;!--Lithium--&gt;
        ///	&lt;Lithium Sekce=&quot;Název&quot; Info=&quot;Lithium&quot; /&gt;
        ///	&lt;Lithium Sekce=&quot;Chemická značka&quot; Info= [rest of string was truncated]&quot;;.
        /// </summary>
        public static string prvky {
            get {
                return ResourceManager.GetString("prvky", resourceCulture);
            }
        }
    }
}
